### ISSUE TITLE
Error trying to log in

### ISSUE THREAD

**Issue by Kristofer1212** [SuperAbhishek/TeleGenisys#1]
UPDATE ::: ERROR TRYING TO FASTK BULK

The v1.py open and closes automatically. All things its configured properly

**Comment by SuperAbhishek** [comment]
Create a folder with name "**Sessions**" in the Script Folder.

**Comment by raviverma86720** [comment]
login sucsful but eroor
please help this error

Enter Your Choice >>>  6

Traceback (most recent call last):
  File "Main.Py", line 7, in <module>
  File "<string>", line 621, in <module>
  File "C:\Users\Ashok Verma\AppData\Local\Programs\Python\Python310\lib\site-packages\telethon\sync.py", line 39, in syncified
    return loop.run_until_complete(coro)
  File "C:\Users\Ashok Verma\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 646, in run_until_complete
    return future.result()
  File "C:\Users\Ashok Verma\AppData\Local\Programs\Python\Python310\lib\site-packages\telethon\client\users.py", line 30, in __call__
    return await self._call(self._sender, request, ordered=ordered)
  File "C:\Users\Ashok Verma\AppData\Local\Programs\Python\Python310\lib\site-packages\telethon\client\users.py", line 84, in _call
    result = await future
telethon.errors.rpcerrorlist.AuthKeyUnregisteredError: The key is not registered in the system (caused by GetDialogsRequest)

**Comment by raviverma86720** [comment]
Enter Your Choice >>>  13

  [i] Total Accounts Available: 2
  [~] Through How Many Account Do You Want To Add Members: 2
  [~] How Many Members Do You Want To Add From Single Account: 40
  [~] Enter Delay Time Per Request [0 for None]: 2

  ______________________________________

 -- Adding Members From 2 Account(s) --

  [i] Start: 0
  [+] User: +917082977294 -- Starting session...
Traceback (most recent call last):
  File "Main.Py", line 7, in <module>
  File "<string>", line 1164, in <module>
AttributeError: 'NoneType' object has no attribute 'first_name'

C:\Users\Ashok Verma\Desktop\TeleGenisys-main (3)\TeleGenisys-main>

**Comment by raviverma86720** [comment]
api id api hash add ?
